import { StyleSheet } from "react-native";

const componentHeight = 180;
export const OutfitDisplayStyles = StyleSheet.create({
	container: {
		position: "relative",
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		height: componentHeight,
		maxHeight: componentHeight,
		borderRadius: 10,
		overflow: "hidden",
		marginTop: 8,
		marginBottom: 8,
		marginLeft: 12,
		marginRight: 12,
		borderRadius: 22,
		borderWidth: 2,
		borderColor: "black",
		borderStyle: "solid",
	},
	image: {
		width: componentHeight,
		height: componentHeight,
		borderBottomRightRadius: 22,
		borderTopRightRadius: 22,
	},
	invisImage: {
		display: "none",
	},
	palletDisplay: {
		display: "flex",
		flexDirection: "column",
		gap: 0,
		margin: 0,
		padding: 0,
		maxWidth: 20,
		width: 20,
		height: componentHeight,
		maxHeight: componentHeight,
	},
	reportImage: {
		width: 20,
		height: 20,
	},
	colorDisplay: {
		display: "flex",
		margin: 0,
		padding: 0,
		border: "none",
		width: 20,
		height: componentHeight / 4,
	},
	sizeButton: {
		position: "absolute",
		top: 8,
		left: 28,
		border: "none",
		zIndex: 2,
		padding: 2,
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
	},
	sizeText: {
		color: "white",
		fontSize: 16,
		opacity: 1,
		fontWeight: "bold",
		textShadowColor: "black",
		textShadowRadius: 10,
		textShadowOffset: { width: 0, height: 0 },
		padding: 6,
		textAlign: "center",
	},
	deleteButton: {
		position: "absolute",
		bottom: 10,
		right: 8,
		backgroundColor: "#5E2478",
		zIndex: 4,
		borderRadius: 20,
		borderWidth: 2,
		borderColor: "black",
		borderStyle: "solid",
		padding: 6,
	},
	deleteText: {
		color: "white",
		fontSize: 12,
		fontWeight: "bold",
		textShadowColor: "pink",
		textShadowRadius: 2,
		textShadowOffset: { width: 1, height: 1 },
		padding: 6,
	},
});
