import { StyleSheet } from "react-native";

export const FeedStyles = StyleSheet.create({
	feedWrapper: {
		flex: 1,
		position: "relative",
	},
	feedPageWrapper: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#9B79EBFF",
	},
	container: {
		flex: 1,
		alignItems: "center",
		justifyContent: "center",
		width: "100%",
		height: "100%",
	},
	text: {
		fontSize: 20,
		color: "orange",
	},
	star1: {
		position: "absolute",
		top: 185,
		left: 6,
		width: 50,
		height: 50,
		zIndex: 0,
		opacity: 0.4,
	},
	star2: {
		position: "absolute",
		bottom: 185,
		left: 6,
		width: 50,
		height: 50,
		zIndex: 0,
		opacity: 0.4,
	},
	star3: {
		position: "absolute",
		top: "50vh",
		left: 0,
		width: 64,
		height: 64,
		zIndex: 0,
		opacity: 0.4,
	},
	star4: {
		position: "absolute",
		top: 185,
		right: 6,
		width: 50,
		height: 50,
		zIndex: 0,
		opacity: 0.6,
	},
	star5: {
		position: "absolute",
		bottom: 185,
		right: 6,
		width: 50,
		height: 50,
		zIndex: 0,
		opacity: 0.6,
	},
	star6: {
		position: "absolute",
		top: "50vh",
		right: 0,
		width: 64,
		height: 64,
		zIndex: 0,
		opacity: 0.6,
	},
	randomGeneratedTag: {
		position: "absolute",
		bottom: 0,
		left: "calc(50% - 50px)",
		width: 320,
		padding: 0,
		paddingTop: 6,
		paddingBottom: 2,
		zIndex: 0,
		borderTopRightRadius: 26,
		borderTopLeftRadius: 26,
		backgroundColor: "#FFBFABFF",
		borderStyle: "solid",
		borderWidth: 2,
		borderColor: "black",
	},
	randomGeneratedText: {
		fontSize: 12,
		fontWeight: "bold",
		color: "white",
		textAlign: "center",
	},
});
