import { StyleSheet } from "react-native";
export const SettingsStyles = StyleSheet.create({
	updatedContainer: {
		position: "absolute",
		top: 40,
		width: 200,
		backgroundColor: "green",
		padding: 10,
		borderRadius: 20,
		left: "50%",
		transform: [{ translateX: -100 }],
		zIndex: 2,
		alignItems: "center",
		display: "flex",
		justifyContent: "center",
	},
	container: {
		display: "flex",
		flex: 1,
		gap: 6,
		paddingTop: 0,
		alignItems: "center",
		justifyContent: "center",
	},
	settingsWrapper: {
		display: "flex",
		flex: 1,
		gap: 6,
		alignItems: "center",
		justifyContent: "center",
		position: "relative",
		top: 70,
	},
	genderContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		position: "relative",
		top: -66,
		gap: 0,
		border: "solid",
		borderColor: "purple",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 0,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		height: 115,
		backgroundColor: "#B1A0D8FF",
		width: 350,
	},
	sectionHeader: {
		fontSize: 22,
		color: "white",
		marginBottom: 6,
		textShadowColor: "#7D55D9FF",
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	sliderHeader: {
		fontSize: 16,
		color: "white",
		marginBottom: 6,
		textShadowColor: "#7D55D9FF",
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	topSizeContainer: {
		display: "flex",
		flexDirection: "column",
		position: "relative",
		top: -60,
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "purple",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 4,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		backgroundColor: "#B1A0D8FF",
		width: 350,
	},
	bottomSizeContainer: {
		display: "flex",
		position: "relative",
		top: -54,
		flexDirection: "column",
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "purple",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 4,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		backgroundColor: "#B1A0D8FF",
		width: 350,
	},
	shoeSizeContainer: {
		display: "flex",
		position: "relative",
		top: -48,
		flexDirection: "column",
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "purple",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 0,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		backgroundColor: "#B1A0D8FF",
		height: 150,
		width: 350,
	},
	text: {
		fontSize: 20,
		color: "white",
	},
	sliderContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 60,
	},
	singleSliderContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 10,
	},
	genderIcon: {
		position: "relative",
		bottom: 36,
		width: 20,
		height: 20,
		padding: 0,
		margin: 0,
		pointerEvents: "none",
		right: 11,
	},
	genderIcon2: {
		position: "relative",
		bottom: 36,
		width: 20,
		height: 20,
		padding: 0,
		margin: 0,
		pointerEvents: "none",
		left: 11,
	},

	topButtonContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginBottom: 10,
	},
	topButtonSelected: {
		backgroundColor: "#3C0750FF",
		borderRadius: 20,
		padding: 6,
		paddingLeft: 10,
		paddingRight: 10,
		borderStyle: "solid",
		borderColor: "purple",
		borderWidth: 1,
	},
	topButtonUnselected: {
		backgroundColor: "white",
		borderRadius: 20,
		padding: 6,
		paddingLeft: 10,
		paddingRight: 10,
		borderStyle: "solid",
		borderColor: "purple",
		borderWidth: 1,
	},
	topTextSelected: {
		color: "white",
	},
	topTextUnselected: {
		color: "black",
	},
	waistInterfaceContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 30,
	},
	waistImage: {
		width: 50,
		height: 50,
		zIndex: 10,
	},
	waistImageRev: {
		width: 50,
		height: 50,
		transform: [{ rotateY: "180deg" }],
	},
	generateFeedText: {
		fontSize: 28,
		color: "#E0D2FDFF",
		textShadowColor: "#7D55D9FF",
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	generateButton: {
		display: "relative",
		backgroundColor: "#3C0750FF",
		border: "dotted",
		top: -36,
		borderColor: "purple",
		borderWidth: 1,
		borderRadius: 20,
		padding: 20,
	},
	customLabel: {
		fontFamily: "Arial",
		fontSize: 10,
	},
	customLabelContainer: {
		width: 80,
		height: 90,
		backgroundColor: "#7D55D9FF",
	},
	shoeSliderContainer: {
		position: "relative",
		bottom: 60,
	},
	shoeSliderTrack: {
		backgroundColor: "grey",
		position: "relative",
		bottom: -28,
	},
	shoeSliderSelected: {
		backgroundColor: "#7D55D9FF",
	},
	shoeSliderMarker: {
		backgroundColor: "purple",
		borderColor: "white",
		borderWidth: 2,
		position: "relative",
		bottom: -28,
		borderStyle: "solid",
	},
});
