import { StyleSheet } from "react-native";

export const SettingsStyles = StyleSheet.create({
	updatedContainer: {
		position: "absolute",
		top: 40,
		width: 200,
		backgroundColor: "green",
		padding: 10,
		borderRadius: 20,
		left: "50%",
		transform: [{ translateX: -100 }],
		zIndex: 2,
		alignItems: "center",
		display: "flex",
		justifyContent: "center",
	},
	container: {
		display: "flex",
		flex: 1,
		gap: 6,
		paddingTop: 80,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: "#7D55D9FF",
	},
	genderContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "black",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 0,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		height: 115,
		backgroundColor: "purple",
		width: 350,
	},
	sectionHeader: {
		fontSize: 20,
		color: "white",
		marginBottom: 6,
	},
	sliderHeader: {
		fontSize: 16,
		color: "white",
		marginBottom: 6,
	},
	topSizeContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "black",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 4,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		backgroundColor: "purple",
		width: 350,
	},
	bottomSizeContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "black",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 4,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		backgroundColor: "purple",
		width: 350,
	},
	shoeSizeContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 0,
		border: "solid",
		borderColor: "black",
		borderWidth: 2,
		paddingTop: 4,
		paddingBottom: 0,
		paddingLeft: 24,
		paddingRight: 24,
		borderRadius: 20,
		backgroundColor: "purple",
		height: 160,
		width: 350,
	},
	text: {
		fontSize: 20,
		color: "white",
	},
	sliderContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 60,
	},
	singleSliderContainer: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: 10,
	},
	genderIcon: {
		position: "relative",
		bottom: 36,
		width: 20,
		height: 20,
		padding: 0,
		margin: 0,
		pointerEvents: "none",
		right: 11,
	},
	genderIcon2: {
		position: "relative",
		bottom: 36,
		width: 20,
		height: 20,
		padding: 0,
		margin: 0,
		pointerEvents: "none",
		left: 11,
	},

	topButtonContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 6,
		marginBottom: 10,
	},
	topButtonSelected: {
		backgroundColor: "#7D55D9FF",
		borderRadius: 20,
		padding: 6,
		paddingLeft: 10,
		paddingRight: 10,
		borderStyle: "solid",
		borderColor: "orange",
		borderWidth: 1,
	},
	topButtonUnselected: {
		backgroundColor: "white",
		borderRadius: 20,
		padding: 6,
		paddingLeft: 10,
		paddingRight: 10,
		borderStyle: "solid",
		borderColor: "orange",
		borderWidth: 1,
	},
	waistInterfaceContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
		gap: 30,
	},
	waistImage: {
		width: 60,
		height: 60,
	},
	waistImageRev: {
		width: 60,
		height: 60,
		transform: [{ rotate: "180deg" }],
	},
	generateFeedText: {
		fontSize: 26,
		color: "white",
		textShadowColor: "black",
		textShadowOffset: { width: 1, height: 1 },
		textShadowRadius: 1,
	},
	generateButton: {
		display: "relative",
		backgroundColor: "#5816A3FF",
		borderStyle: "solid",
		borderColor: "black",
		borderWidth: 2,
		borderRadius: 20,
		padding: 30,
	},
	customLabel: {
		fontFamily: "Arial",
		fontSize: 10,
	},
	customLabelContainer: {
		width: 80,
		height: 90,
		backgroundColor: "purple",
	},
	shoeSliderContainer: {
		position: "relative",
		bottom: 60,
	},
	shoeSliderTrack: {
		backgroundColor: "grey",
	},
	shoeSliderSelected: {
		backgroundColor: "#7D55D9FF",
	},
	shoeSliderMarker: {
		backgroundColor: "purple",
		borderColor: "white",
		borderWidth: 2,
		borderStyle: "solid",
	},
});
