import { StyleSheet } from "react-native";

export const LogInStyles = StyleSheet.create({
	container: {
		display: "flex",
		flexDirection: "column",
		height: "100%",
		justifyContent: "flex-start",
		alignItems: "center",
		gap: 0,
		backgroundColor: "#9B79EBFF",
	},
	text: {
		fontSize: 22,
		color: "#F5D6FFFF",
		textShadowColor: "#6C018DFF",
		textShadowRadius: 2,
		textShadowOffset: { width: 1, height: 1 },
		display: "inline-block",
		textAlign: "center",
	},
	header: {
		position: "relative",
		top: 60,
		marginTop: 500,
		fontSize: 48,
		fontWeight: "bold",
		color: "#F5D6FFFF",
		textShadowColor: "#6C018DFF",
		textShadowRadius: 5,
		textShadowOffset: { width: 2, height: 2 },
		width: 220,
		textAlign: "center",
		marginTop: 0,
	},
	image: {
		width: 260,
		height: 260,
		position: "relative",
		top: 80,
	},
	button: {
		backgroundColor: "#7E00E4FF",
		borderRadius: 40,
		paddingTop: 10,
		paddingBottom: 10,
		width: 150,
		paddingLeft: 8,
		padddingRight: 8,
		margin: 10,
		borderStyle: "solid",
		borderWidth: 2,
		borderColor: "#420F6CFF",
		position: "relative",
		top: 140,
	},
});
